# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: George N. Spingos
title: Senior Software Architect
email: george.spingos@gmail.com
website: https://georgespingos.github.io./

# Social links
#twitter_username: facespics
#github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: george-spingos-631590113
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Senior manager with extensive experience in software engineering, system design and team management, recruiting and developing engineering talent into high performance teams using agile development practices. Lead for recruitment efforts targeting senior technology roles.

# Experience Section
experience_title: Work Experience

# More Section
more_title: Skills
more_content: | # this will include new lines to allow paragraphs
  ![](https://i.ibb.co/sjY8Fqz/skills.png)

# Education Section
educaton_title: Education


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
