# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: George N. Spingos
title: Senior Software Architect
email: george.spingos@gmail.com
website: https://georgespingos.github.io./

# Social links
#twitter_username: facespics
#github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: george-spingos-631590113
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg

# Experience Section
experience_title: Work Experience


about_content: | # this will include new lines to allow paragraphs
  Senior manager with extensive experience in software engineering, system design and team management, recruiting and developing engineering talent. Lead for recruitment efforts targeting senior technology roles.

  My focus is on the technical side is distributed systems architecture and [scaling](https://observablehq.com/@gnsping/scaling-onboarding-quantitative-approach) and managing teams, [organization design](https://observablehq.com/@gnsping/scaling-onboarding-a-quantitative-approach-part-ii) and technical strategy.


# More Section
more_title: Skills
more_content: | # this will include new lines to allow paragraphs
  ![](https://lh3.googleusercontent.com/pw/ACtC-3ewqkwbIEhIIfL8eEfOu6_owQgy5C2RhGxnFTwA-WiGsVugmsA1hNuqaJ8kGX40Sujd14tFMrG1-9Lq8ur4fcFb5fpfLNj8Qb39mB7KSdMnF-YFW5h4eJ92HWCOh1iZMmFzppEowtwWJTNCFn2RJKL8=w781-h190-no)

# Education Section
educaton_title: Education


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
